import Link from "next/link";
import { redirect } from "next/navigation";
import { createClient } from "@/lib/db/supabase-server";
import { requireUser } from "@/lib/auth/get-user";
import { getActiveOrganization, canManageReports } from "@/lib/organizations/get-organization";
import { getReport } from "@/lib/reports/get-reports";
import ArchiveReportButton from "@/components/reports/archive-report-button";
import ReportContentView from "@/components/reports/report-content-view";

const REPORT_TYPE_LABELS: Record<string, string> = {
  player_summary: "Player Summary",
  team_summary: "Team Summary",
  session_summary: "Session Summary",
  match_summary: "Match Summary",
  assessment_summary: "Assessment Summary",
};

const SOURCE_ENTITY_LABELS: Record<string, string> = {
  player: "Player",
  team: "Team",
  training_session: "Training Session",
  match: "Match",
  assessment: "Assessment Result",
};

function StatusBadge({ status }: { status: string }) {
  const styles: Record<string, string> = {
    generated:
      "inline-flex items-center rounded-full px-2.5 py-0.5 text-xs font-medium bg-green-100 text-green-800 dark:bg-green-900/30 dark:text-green-400",
    draft:
      "inline-flex items-center rounded-full px-2.5 py-0.5 text-xs font-medium bg-zinc-100 text-zinc-600 dark:bg-zinc-800 dark:text-zinc-400",
    archived:
      "inline-flex items-center rounded-full px-2.5 py-0.5 text-xs font-medium bg-zinc-200 text-zinc-500 dark:bg-zinc-700 dark:text-zinc-400",
  };
  return (
    <span className={styles[status] ?? styles.draft}>
      {status.charAt(0).toUpperCase() + status.slice(1)}
    </span>
  );
}

interface ReportPageProps {
  params: Promise<{ reportId: string }>;
}

export default async function ReportPage({ params }: ReportPageProps) {
  const { reportId } = await params;

  const user = await requireUser();
  const supabase = await createClient();
  if (!supabase) redirect("/login");

  const activeOrg = await getActiveOrganization(supabase, user.id);
  if (!activeOrg) redirect("/setup/organization");

  const [report, canManage] = await Promise.all([
    getReport(supabase, reportId, activeOrg.organizationId),
    canManageReports(supabase, user.id, activeOrg.organizationId),
  ]);

  if (!report) redirect("/reports");

  return (
    <div className="flex flex-col gap-6">
      <div className="flex items-start justify-between gap-4">
        <div>
          <Link
            href="/reports"
            className="text-sm text-zinc-500 hover:text-zinc-700 dark:text-zinc-400 dark:hover:text-zinc-200"
          >
            ← Back to reports
          </Link>
          <h1 className="mt-2 text-2xl font-semibold text-zinc-900 dark:text-zinc-50">
            {report.title}
          </h1>
        </div>
        {canManage && !report.isArchived && (
          <div className="mt-8 shrink-0">
            <ArchiveReportButton
              organizationId={activeOrg.organizationId}
              reportId={report.id}
            />
          </div>
        )}
      </div>

      <div className="rounded-lg border border-zinc-200 bg-white p-6 dark:border-zinc-800 dark:bg-zinc-900">
        <dl className="grid grid-cols-2 gap-x-8 gap-y-4 sm:grid-cols-3">
          <div>
            <dt className="text-xs font-medium uppercase tracking-wide text-zinc-500 dark:text-zinc-400">
              Type
            </dt>
            <dd className="mt-1 text-sm text-zinc-900 dark:text-zinc-50">
              {REPORT_TYPE_LABELS[report.reportType] ?? report.reportType}
            </dd>
          </div>
          <div>
            <dt className="text-xs font-medium uppercase tracking-wide text-zinc-500 dark:text-zinc-400">
              Status
            </dt>
            <dd className="mt-1">
              <StatusBadge status={report.status} />
            </dd>
          </div>
          {report.sourceEntityType && (
            <div>
              <dt className="text-xs font-medium uppercase tracking-wide text-zinc-500 dark:text-zinc-400">
                Source
              </dt>
              <dd className="mt-1 text-sm text-zinc-900 dark:text-zinc-50">
                {SOURCE_ENTITY_LABELS[report.sourceEntityType] ?? report.sourceEntityType}
              </dd>
            </div>
          )}
          <div>
            <dt className="text-xs font-medium uppercase tracking-wide text-zinc-500 dark:text-zinc-400">
              Created
            </dt>
            <dd className="mt-1 text-sm text-zinc-900 dark:text-zinc-50">
              {new Date(report.createdAt).toLocaleDateString()}
            </dd>
          </div>
          {report.generatedBy && (
            <div>
              <dt className="text-xs font-medium uppercase tracking-wide text-zinc-500 dark:text-zinc-400">
                Generated by
              </dt>
              <dd className="mt-1 text-sm text-zinc-500 dark:text-zinc-400 font-mono text-xs">
                {report.generatedBy}
              </dd>
            </div>
          )}
        </dl>

        {report.summary && (
          <div className="mt-6 border-t border-zinc-100 pt-6 dark:border-zinc-800">
            <h2 className="mb-2 text-sm font-medium text-zinc-700 dark:text-zinc-300">Summary</h2>
            <p className="text-sm text-zinc-600 dark:text-zinc-400">{report.summary}</p>
          </div>
        )}

        <div className="mt-6 border-t border-zinc-100 pt-6 dark:border-zinc-800">
          <h2 className="mb-3 text-sm font-medium text-zinc-700 dark:text-zinc-300">
            Structured content
          </h2>
          <ReportContentView content={report.content} />
        </div>
      </div>
    </div>
  );
}
