import { Text, View } from "@react-pdf/renderer";
import { styles } from "./styles";
import type { ReportDetailRow } from "@/lib/reports/get-reports";

export function asArray<T = Record<string, unknown>>(value: unknown): T[] {
  return Array.isArray(value) ? (value as T[]) : [];
}

export function asRecord(value: unknown): Record<string, unknown> | null {
  return value && typeof value === "object" && !Array.isArray(value)
    ? (value as Record<string, unknown>)
    : null;
}

export function formatKey(key: string): string {
  return key
    .split("_")
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(" ");
}

export function formatValue(value: unknown): string {
  if (value === null || value === undefined || value === "") return "—";
  if (typeof value === "boolean") return value ? "Yes" : "No";
  if (typeof value === "object") return JSON.stringify(value);
  return String(value);
}

interface ReportHeaderProps {
  reportTypeLabel: string;
  report: ReportDetailRow;
}

export function ReportHeader({ reportTypeLabel, report }: ReportHeaderProps) {
  return (
    <View>
      <Text style={styles.eyebrow}>{reportTypeLabel}</Text>
      <Text style={styles.title}>{report.title}</Text>
      <View style={styles.metaRow}>
        <View style={styles.metaItem}>
          <Text style={styles.metaLabel}>Status</Text>
          <Text style={styles.metaValue}>{formatValue(report.status)}</Text>
        </View>
        <View style={styles.metaItem}>
          <Text style={styles.metaLabel}>Created</Text>
          <Text style={styles.metaValue}>
            {new Date(report.createdAt).toLocaleDateString()}
          </Text>
        </View>
        {report.generatedBy && (
          <View style={styles.metaItem}>
            <Text style={styles.metaLabel}>Generated by</Text>
            <Text style={styles.metaValue}>{report.generatedBy}</Text>
          </View>
        )}
      </View>
      {report.summary && (
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Summary</Text>
          <Text style={styles.paragraph}>{report.summary}</Text>
        </View>
      )}
    </View>
  );
}

interface KeyValueSectionProps {
  title: string;
  data: Record<string, unknown> | null | undefined;
  omitKeys?: string[];
}

export function KeyValueSection({ title, data, omitKeys = [] }: KeyValueSectionProps) {
  const entries = data
    ? Object.entries(data).filter(([key]) => !omitKeys.includes(key))
    : [];

  return (
    <View style={styles.section}>
      <Text style={styles.sectionTitle}>{title}</Text>
      {entries.length === 0 ? (
        <Text style={styles.emptyState}>Not available.</Text>
      ) : (
        entries.map(([key, value]) => (
          <View key={key} style={styles.kvRow}>
            <Text style={styles.kvKey}>{formatKey(key)}</Text>
            <Text style={styles.kvValue}>{formatValue(value)}</Text>
          </View>
        ))
      )}
    </View>
  );
}

interface DataTableColumn<T> {
  key: keyof T;
  label: string;
  width?: string | number;
}

interface DataTableProps<T extends Record<string, unknown>> {
  title: string;
  columns: DataTableColumn<T>[];
  rows: T[] | null | undefined;
  emptyLabel?: string;
}

export function DataTable<T extends Record<string, unknown>>({
  title,
  columns,
  rows,
  emptyLabel = "No records available.",
}: DataTableProps<T>) {
  const safeRows = rows ?? [];
  return (
    <View style={styles.section} wrap={false}>
      <Text style={styles.sectionTitle}>{title}</Text>
      {safeRows.length === 0 ? (
        <Text style={styles.emptyState}>{emptyLabel}</Text>
      ) : (
        <View style={styles.table}>
          <View style={styles.tableHeaderRow}>
            {columns.map((col) => (
              <Text
                key={String(col.key)}
                style={[styles.tableHeaderCell, { width: col.width ?? `${100 / columns.length}%` }]}
              >
                {col.label}
              </Text>
            ))}
          </View>
          {safeRows.map((row, idx) => (
            <View key={idx} style={styles.tableRow}>
              {columns.map((col) => (
                <Text
                  key={String(col.key)}
                  style={[styles.tableCell, { width: col.width ?? `${100 / columns.length}%` }]}
                >
                  {formatValue(row[col.key])}
                </Text>
              ))}
            </View>
          ))}
        </View>
      )}
    </View>
  );
}

export function ReportFooter() {
  return (
    <View style={styles.footer} fixed>
      <Text>Coplanio</Text>
      <Text
        render={({ pageNumber, totalPages }) => `Page ${pageNumber} of ${totalPages}`}
      />
    </View>
  );
}
